--liquibase formatted sql;

--changeset styulkov:1
CREATE TABLE IF NOT EXISTS notification
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT NOT NULL,
    notification_date TIMESTAMP NOT NULL,
    message TEXT NOT NULL,
    status VARCHAR (255) NOT NULL DEFAULT 'SCHEDULED',
);

CREATE INDEX notification_date_index ON notification (notification_date) WHERE status = 'SCHEDULED';